# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170530_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo1',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='u2g',
            field=models.ManyToManyField(to='app01.UserGroup'),
        ),
    ]
