# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('PYTHON\u6280\u672f', 'python\u6280\u672f'), ('\u6570\u636e\u5e93\u6280\u672f', '\u6570\u636e\u5e93\u6280\u672f'), ('\u7ecf\u6d4e\u5b66', '\u7ecf\u6d4e\u5b66'), ('\u4e2a\u4eba\u5fc3\u60c5', '\u4e2a\u4eba\u5fc3\u60c5'), ('\u5176\u4ed6', '\u5176\u4ed6')], default=('PYTHON\u6280\u672f', 'python\u6280\u672f'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='\u533f\u540d', max_length=20),
        ),
    ]
